# Шаблон для запуска подов (NestJS или Go)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-products
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: nestjs-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          
          # Kubernetes проверяет, не завис ли процесс [INDEX 4]
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          # Kubernetes проверяет, готов ли сервис (БД и Redis подключены) [INDEX 2]
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

